accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

chatbot/urls.py
from django.urls import path

from . import views

app_name = 'chatbot'
urlpatterns = [
    path('', views.index, name='index'),
    path('chat/', views.chat, name='chat'),
    path('limparhistorico/', views.limpar_historico, name='limpar_historico'),
]

settings/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chatbot.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render


# Create your views here.
def login(request):
    template_name = 'accounts/pages/login.html'
    if request.method != 'POST':
        return render(request, template_name)

    username = request.POST.get('username')
    password = request.POST.get('password')

    user = auth.authenticate(request, username=username, password=password)

    if not user:
        messages.error(request, 'Invalid username or password')
        return render(request, template_name)

    else:
        auth.login(request, user)
        return redirect('chatbot:index')


@login_required(login_url='accounts:login', redirect_field_name='next')
def logout(request):
    auth.logout(request)
    return redirect('accounts:login')

accounts/templates/accounts/pages/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login EcoMart</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" />
  </head>
  <style>
    html,
    body {
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      height: 100vh;
      background: linear-gradient(to bottom, #01080e, #144480);
      font-family: 'Inter', sans-serif;
    }
    main {
      position: relative;
      padding-top: 10%;
    }
    .form-signin {
      max-width: 330px;
    }
    
    .form-signin .form-floating:focus-within {
      z-index: 2;
    }
    
    .form-signin input[type='email'] {
      margin-bottom: -1px;
      border-bottom-right-radius: 0;
      border-bottom-left-radius: 0;
    }
    
    .form-signin input[type='password'] {
      margin-bottom: 10px;
      border-top-left-radius: 0;
      border-top-right-radius: 0;
    }
    a {
      color: #FFFFFF;
      text-decoration: none;
    }
  </style>
  <body class="d-flex align-items-center py-4 bg-body-tertiary">
    {% include "../partials/_messeges.html" %}
    <main class="form-signin w-100 m-auto">
      {% if user.is_authenticated %}
        <h1 class="text-light text-center">You are already logged in</h1>
        <div class="text-center">
          <a href="{% url 'accounts:logout' %}" class="btn btn-primary">Logout</a>
          <a href="{% url 'chatbot:index' %}" class="btn btn-secondary">Home</a>
        </div>
        {% else %}
        
        <h1 class="h3 mb-3 text-light">Please sign in</h1>
        <form action="{% url 'accounts:login' %}" method="POST">
          {% csrf_token %}
          <div class="form-floating mb-3">
            <input type="text" class="form-control" name="username" />
            <label>Username</label>
          </div>
          <div class="form-floating">
            <input type="password" class="form-control" name="password" />
            <label>Password</label>
          </div>
          <button class="btn btn-primary w-100 py-2" type="submit">Sign in</button>
          <div class="text-center py-3">
            <a href="https://github.com/HeitorLouzeiro" target="_blank">Git Hub</a> /
            <a href="https://www.linkedin.com/in/heitor-louzeiro/" target="_blank">Linkedin</a>
          </div>
          </form>
      {% endif %}
    </main>
  </body>
</html>